### ISSUE TITLE
m32_v5.ino - error: 'jsonConfigLong' was not declared in this scope

### ISSUE THREAD

**Issue by AdamZiegler** [fred777/Morserino-32_Heltec-v3#1]
I kept running into build errors on platformio in file m32_v5.ino "error: 'jsonConfigLong' was not declared in this scope".  Moving the function up in the file before it was called allowed the build to continue and had a successful upload to the V3 heltec board.   Maybe there are better solutions, but I am new to platformio.  Need to still test with hardware connections now.

**Comment by fred777** [comment]
Ah, right - I once had the declaration of that function on the top of the file when I tried to convert the .ino file into a true .cpp file but gave up at some point. My last commit removed that in an attempt to clean up things but apparently this was wrong.

=> it's fixed now with my recent commit.
